version: '3'

services:
  app:
    build:
      context: .
      dockerfile: deployment/Dockerfile.dev
      args:
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_HOST: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME}
    container_name: zeta-api-container
    working_dir: /app
    ports:
     - "8080:8080"
    depends_on:
     - db

  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATBASE: manu
    ports:
     - "3306:3306"

networks:
  default:
    driver: bridge