version: '3'

services:
  app:
    build:
      context: .
      dockerfile: deployment/Dockerfile.dev
    env_file:
      - .env
    container_name: zeta-api-container
    working_dir: /app
    ports:
     - "8081:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: manu
    ports:
     - "3307:3306"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://mysql:3306"]
      timeout: 20s
      retries: 10

networks:
  default:
    driver: bridge
