info:
  contact: {}
paths:
  /video:
    post:
      parameters:
      - description: Vidoe File
        in: formData
        name: video
        required: true
        type: file
      produces:
      - application/json
      responses: {}
      summary: Upload a video
swagger: "2.0"
