info:
  contact: {}
paths:
  /postVideo:
    post:
      consumes:
      - multipart/form-data
      description: Uploads a video file and processes it
      parameters:
      - description: Vidoe File
        in: formData
        name: video
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: File uploaded successfully
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Upload a video
  /uploadtoS3:
    post:
      consumes:
      - multipart/form-data
      description: Uploads a file to S3 bucket
      parameters:
      - description: File to upload
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: File uploaded successfully
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Save video to S3
swagger: "2.0"
