basePath: /api
definitions:
  entity.ErrorWrapper:
    properties:
      error: {}
    type: object
  entity.ResponseWrapper:
    properties:
      data: {}
    type: object
  entity.TranslateJson:
    properties:
      targetLanguage:
        type: string
      text:
        type: string
    type: object
  valueobjects.TranslateControllerOutput:
    properties:
      originalText:
        type: string
      translatedText:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: server
  title: Manu Swagger API
  version: "1.0"
paths:
  /predict:
    post:
      consumes:
      - multipart/form-data
      description: Uploads a video file to S3 and prepares it for machine learning
        prediction
      parameters:
      - default: Bearer <Add access token here>
        description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: Video file to upload
        in: formData
        name: video
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      - BearerAuth: []
      summary: Upload a video for prediction
      tags:
      - api
  /translate:
    post:
      consumes:
      - application/json
      description: Translates the provided text into the target language
      parameters:
      - description: Translation request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/entity.TranslateJson'
      produces:
      - application/json
      responses:
        "200":
          description: Successful operation
          schema:
            allOf:
            - $ref: '#/definitions/entity.ResponseWrapper'
            - properties:
                data:
                  $ref: '#/definitions/valueobjects.TranslateControllerOutput'
              type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/entity.ErrorWrapper'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/entity.ErrorWrapper'
      summary: Translate text
swagger: "2.0"
